### PR TITLE
Include base parameters in json file for testing

### PR DESCRIPTION
**Pull request by blakecaldwell**
To be used in test for PR #80

### CODE REVIEW

**Comment by jasmainak** [comment]
@blakecaldwell is this different from `default.json`?

**Comment by blakecaldwell** [comment]
@jasmainak yes, this is different. it's just the base params from get_params_default()

**Comment by blakecaldwell** [comment]
@jasmainak please merge for testing of #80 to succeed

**Comment by jasmainak** [comment]
Thanks @blakecaldwell

**Pull request merged**
